name: Release Edge Extension

on:
  workflow_dispatch:
  push:
    paths:
      - "chrome-extension/manifest.json"

permissions:
  contents: read

concurrency:
  group: release-edge-extension
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Package extension zip
        working-directory: chrome-extension
        run: zip -r ../extension.zip .

      - name: Publish Edge Add-on
        uses: baptistecdr/release-edge-extension@v2.1.0
        with:
          api-key: ${{ secrets.EDGE_API_KEY }}
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          product-id: "2e21bb95-3850-495a-9fd1-c2c7811c1dae"
          product-path: "./extension.zip"
